// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string):Promise<void>;

export function Blacklist(arg1:string):Promise<void>;

export function CheckDaemonStatus():Promise<boolean>;

export function DeleteWallpaper(arg1:string):Promise<void>;

export function Download(arg1:string):Promise<void>;

export function GetConfigPath():Promise<string>;

export function GetMonitors():Promise<Array<main.Monitor>>;

export function Greet(arg1:string):Promise<string>;

export function Initialize():Promise<void>;

export function LoadConfig():Promise<main.GowerConfig>;

export function LoadCurrentWallpapers():Promise<Array<main.Wallpaper>>;

export function LoadFavorites(arg1:string):Promise<Array<main.Wallpaper>>;

export function LoadFeed(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<main.Wallpaper>>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenFolderPicker():Promise<string>;

export function OpenImageExternally(arg1:string,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<main.Wallpaper>>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetNextWallpaper():Promise<void>;

export function SetWallpaper(arg1:string,arg2:string):Promise<void>;

export function ToggleDaemon(arg1:boolean):Promise<void>;

export function UndoWallpaper():Promise<void>;

export function UpdateFeed():Promise<void>;
