// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function Blacklist(arg1) {
  return window['go']['main']['App']['Blacklist'](arg1);
}

export function CheckDaemonStatus() {
  return window['go']['main']['App']['CheckDaemonStatus']();
}

export function DeleteWallpaper(arg1) {
  return window['go']['main']['App']['DeleteWallpaper'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadCurrentWallpapers() {
  return window['go']['main']['App']['LoadCurrentWallpapers']();
}

export function LoadFavorites(arg1) {
  return window['go']['main']['App']['LoadFavorites'](arg1);
}

export function LoadFeed(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadFeed'](arg1, arg2, arg3, arg4);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function OpenImageExternally(arg1, arg2) {
  return window['go']['main']['App']['OpenImageExternally'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetNextWallpaper() {
  return window['go']['main']['App']['SetNextWallpaper']();
}

export function SetWallpaper(arg1, arg2) {
  return window['go']['main']['App']['SetWallpaper'](arg1, arg2);
}

export function ToggleDaemon(arg1) {
  return window['go']['main']['App']['ToggleDaemon'](arg1);
}

export function UndoWallpaper() {
  return window['go']['main']['App']['UndoWallpaper']();
}

export function UpdateFeed() {
  return window['go']['main']['App']['UpdateFeed']();
}
