// Code generated by internal/genconfig; DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
)

// ConfigPathEntry describes a single config path.
type ConfigPathEntry struct {
	Path string
	Type string
}

// ListConfigPaths returns all available configuration paths.
func ListConfigPaths() []ConfigPathEntry {
	return []ConfigPathEntry{
		{Path: "providers.wallhaven.enabled", Type: "bool"},
		{Path: "providers.wallhaven.api_key", Type: "string"},
		{Path: "providers.wallhaven.rate_limit.requests", Type: "int"},
		{Path: "providers.wallhaven.rate_limit.per_seconds", Type: "int"},
		{Path: "providers.reddit.enabled", Type: "bool"},
		{Path: "providers.reddit.subreddit", Type: "string"},
		{Path: "providers.reddit.sort", Type: "string"},
		{Path: "providers.reddit.limit", Type: "int"},
		{Path: "providers.nasa.enabled", Type: "bool"},
		{Path: "providers.nasa.api_key", Type: "string"},
		{Path: "providers.bing.enabled", Type: "bool"},
		{Path: "providers.bing.market", Type: "string"},
		{Path: "providers.unsplash.enabled", Type: "bool"},
		{Path: "providers.unsplash.api_key", Type: "string"},
		{Path: "search.min_width", Type: "int"},
		{Path: "search.min_height", Type: "int"},
		{Path: "search.aspect_ratio", Type: "string"},
		{Path: "search.tolerance", Type: "float64"},
		{Path: "behavior.theme", Type: "string"},
		{Path: "behavior.change_interval", Type: "int"},
		{Path: "behavior.multi_monitor", Type: "string"},
		{Path: "behavior.auto_download", Type: "bool"},
		{Path: "behavior.respect_dark_mode", Type: "bool"},
		{Path: "behavior.save_favorites_to_folder", Type: "bool"},
		{Path: "behavior.from_favorites", Type: "bool"},
		{Path: "paths.wallpapers", Type: "string"},
		{Path: "paths.index_wallpapers", Type: "bool"},
		{Path: "ui.show_colors", Type: "bool"},
		{Path: "ui.items_per_page", Type: "int"},
		{Path: "limits.feed_soft_limit", Type: "int"},
		{Path: "limits.feed_hard_limit", Type: "int"},
		{Path: "limits.rate_limit_requests", Type: "int"},
		{Path: "limits.rate_limit_period", Type: "int"},
		{Path: "limits.log_retention_days", Type: "int"},
		{Path: "limits.analysis_workers", Type: "int"},
		{Path: "dry_run", Type: "bool"},
	}
}

// SetConfigValue sets a configuration value by dotted path.
func SetConfigValue(cfg *Config, path string, value string) error {
	switch path {
	case "providers.wallhaven.enabled":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Wallhaven.Enabled = v
		return nil
	case "providers.wallhaven.api_key":
		cfg.Providers.Wallhaven.APIKey = value
		return nil
	case "providers.wallhaven.rate_limit.requests":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Wallhaven.RateLimit.Requests = v
		return nil
	case "providers.wallhaven.rate_limit.per_seconds":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Wallhaven.RateLimit.PerSeconds = v
		return nil
	case "providers.reddit.enabled":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Reddit.Enabled = v
		return nil
	case "providers.reddit.subreddit":
		cfg.Providers.Reddit.Subreddit = value
		return nil
	case "providers.reddit.sort":
		cfg.Providers.Reddit.Sort = value
		return nil
	case "providers.reddit.limit":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Reddit.Limit = v
		return nil
	case "providers.nasa.enabled":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Nasa.Enabled = v
		return nil
	case "providers.nasa.api_key":
		cfg.Providers.Nasa.APIKey = value
		return nil
	case "providers.bing.enabled":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Bing.Enabled = v
		return nil
	case "providers.bing.market":
		cfg.Providers.Bing.Market = value
		return nil
	case "providers.unsplash.enabled":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Providers.Unsplash.Enabled = v
		return nil
	case "providers.unsplash.api_key":
		cfg.Providers.Unsplash.APIKey = value
		return nil
	case "search.min_width":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Search.MinWidth = v
		return nil
	case "search.min_height":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Search.MinHeight = v
		return nil
	case "search.aspect_ratio":
		cfg.Search.AspectRatio = value
		return nil
	case "search.tolerance":
		v, err := strconv.ParseFloat(value, 64)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Search.Tolerance = v
		return nil
	case "behavior.theme":
		cfg.Behavior.Theme = value
		return nil
	case "behavior.change_interval":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Behavior.ChangeInterval = v
		return nil
	case "behavior.multi_monitor":
		cfg.Behavior.MultiMonitor = value
		return nil
	case "behavior.auto_download":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Behavior.AutoDownload = v
		return nil
	case "behavior.respect_dark_mode":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Behavior.RespectDarkMode = v
		return nil
	case "behavior.save_favorites_to_folder":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Behavior.SaveFavoritesToFolder = v
		return nil
	case "behavior.from_favorites":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Behavior.FromFavorites = v
		return nil
	case "paths.wallpapers":
		cfg.Paths.Wallpapers = value
		return nil
	case "paths.index_wallpapers":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Paths.IndexWallpapers = v
		return nil
	case "ui.show_colors":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.UI.ShowColors = v
		return nil
	case "ui.items_per_page":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.UI.ItemsPerPage = v
		return nil
	case "limits.feed_soft_limit":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.FeedSoftLimit = v
		return nil
	case "limits.feed_hard_limit":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.FeedHardLimit = v
		return nil
	case "limits.rate_limit_requests":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.RateLimitRequests = v
		return nil
	case "limits.rate_limit_period":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.RateLimitPeriod = v
		return nil
	case "limits.log_retention_days":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.LogRetentionDays = v
		return nil
	case "limits.analysis_workers":
		v, err := strconv.Atoi(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.Limits.AnalysisWorkers = v
		return nil
	case "dry_run":
		v, err := strconv.ParseBool(value)
		if err != nil {
			return fmt.Errorf("invalid value for %s: %v", path, err)
		}
		cfg.DryRun = v
		return nil
	default:
		return fmt.Errorf("unknown config path: %s", path)
	}
}

// GetConfigValue returns a configuration value by dotted path.
func GetConfigValue(cfg *Config, path string) (string, error) {
	switch path {
	case "providers.wallhaven.enabled":
		return strconv.FormatBool(cfg.Providers.Wallhaven.Enabled), nil
	case "providers.wallhaven.api_key":
		return cfg.Providers.Wallhaven.APIKey, nil
	case "providers.wallhaven.rate_limit.requests":
		return strconv.Itoa(cfg.Providers.Wallhaven.RateLimit.Requests), nil
	case "providers.wallhaven.rate_limit.per_seconds":
		return strconv.Itoa(cfg.Providers.Wallhaven.RateLimit.PerSeconds), nil
	case "providers.reddit.enabled":
		return strconv.FormatBool(cfg.Providers.Reddit.Enabled), nil
	case "providers.reddit.subreddit":
		return cfg.Providers.Reddit.Subreddit, nil
	case "providers.reddit.sort":
		return cfg.Providers.Reddit.Sort, nil
	case "providers.reddit.limit":
		return strconv.Itoa(cfg.Providers.Reddit.Limit), nil
	case "providers.nasa.enabled":
		return strconv.FormatBool(cfg.Providers.Nasa.Enabled), nil
	case "providers.nasa.api_key":
		return cfg.Providers.Nasa.APIKey, nil
	case "providers.bing.enabled":
		return strconv.FormatBool(cfg.Providers.Bing.Enabled), nil
	case "providers.bing.market":
		return cfg.Providers.Bing.Market, nil
	case "providers.unsplash.enabled":
		return strconv.FormatBool(cfg.Providers.Unsplash.Enabled), nil
	case "providers.unsplash.api_key":
		return cfg.Providers.Unsplash.APIKey, nil
	case "search.min_width":
		return strconv.Itoa(cfg.Search.MinWidth), nil
	case "search.min_height":
		return strconv.Itoa(cfg.Search.MinHeight), nil
	case "search.aspect_ratio":
		return cfg.Search.AspectRatio, nil
	case "search.tolerance":
		return strconv.FormatFloat(cfg.Search.Tolerance, 'f', -1, 64), nil
	case "behavior.theme":
		return cfg.Behavior.Theme, nil
	case "behavior.change_interval":
		return strconv.Itoa(cfg.Behavior.ChangeInterval), nil
	case "behavior.multi_monitor":
		return cfg.Behavior.MultiMonitor, nil
	case "behavior.auto_download":
		return strconv.FormatBool(cfg.Behavior.AutoDownload), nil
	case "behavior.respect_dark_mode":
		return strconv.FormatBool(cfg.Behavior.RespectDarkMode), nil
	case "behavior.save_favorites_to_folder":
		return strconv.FormatBool(cfg.Behavior.SaveFavoritesToFolder), nil
	case "behavior.from_favorites":
		return strconv.FormatBool(cfg.Behavior.FromFavorites), nil
	case "paths.wallpapers":
		return cfg.Paths.Wallpapers, nil
	case "paths.index_wallpapers":
		return strconv.FormatBool(cfg.Paths.IndexWallpapers), nil
	case "ui.show_colors":
		return strconv.FormatBool(cfg.UI.ShowColors), nil
	case "ui.items_per_page":
		return strconv.Itoa(cfg.UI.ItemsPerPage), nil
	case "limits.feed_soft_limit":
		return strconv.Itoa(cfg.Limits.FeedSoftLimit), nil
	case "limits.feed_hard_limit":
		return strconv.Itoa(cfg.Limits.FeedHardLimit), nil
	case "limits.rate_limit_requests":
		return strconv.Itoa(cfg.Limits.RateLimitRequests), nil
	case "limits.rate_limit_period":
		return strconv.Itoa(cfg.Limits.RateLimitPeriod), nil
	case "limits.log_retention_days":
		return strconv.Itoa(cfg.Limits.LogRetentionDays), nil
	case "limits.analysis_workers":
		return strconv.Itoa(cfg.Limits.AnalysisWorkers), nil
	case "dry_run":
		return strconv.FormatBool(cfg.DryRun), nil
	default:
		return "", fmt.Errorf("unknown config path: %s", path)
	}
}
