package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type FieldPath struct {
	Path      string // dotted json path, e.g. "providers.wallhaven.enabled"
	GoType    string // bool, string, int, float64
	GoField   string // full Go field expression, e.g. "cfg.Providers.Wallhaven.Enabled"
	IsStruct  bool
	Children  []FieldPath
}

func main() {
	// Determine project root: walk up until we find go.mod
	wd, _ := os.Getwd()
	root := wd
	for {
		if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			panic("go.mod not found")
		}
		root = parent
	}
	configPath := filepath.Join(root, "pkg", "models", "config.go")

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, configPath, nil, parser.ParseComments)
	if err != nil {
		panic(fmt.Sprintf("failed to parse %s: %v", configPath, err))
	}

	// Find all type declarations
	typeMap := make(map[string]*ast.StructType)
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if ok {
				typeMap[typeSpec.Name.Name] = structType
			}
		}
	}

	// Start from Config struct
	rootStruct, ok := typeMap["Config"]
	if !ok {
		panic("Config struct not found")
	}

	paths := buildPaths(typeMap, "Config", "cfg", []string{}, rootStruct)

	generate(paths, root, fset)
}

func buildPaths(typeMap map[string]*ast.StructType, typeName, goPrefix string, jsonPrefix []string, st *ast.StructType) []FieldPath {
	var result []FieldPath

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name

		// Get json tag
		jsonTag := ""
		if field.Tag != nil {
			tag := field.Tag.Value
			tag = strings.Trim(tag, "`")
			for _, t := range strings.Fields(tag) {
				if strings.HasPrefix(t, "json:") {
					jsonTag = strings.TrimPrefix(t, "json:")
					jsonTag = strings.Trim(jsonTag, "\"")
					// Remove omitempty etc.
					if idx := strings.Index(jsonTag, ","); idx != -1 {
						jsonTag = jsonTag[:idx]
					}
				}
			}
		}
		if jsonTag == "" || jsonTag == "-" {
			continue
		}

		newJSONPrefix := append(jsonPrefix, jsonTag)
		newGoPrefix := goPrefix + "." + fieldName

		goType := exprToString(field.Type)

		if structType, ok := typeMap[goType]; ok {
			children := buildPaths(typeMap, goType, newGoPrefix, newJSONPrefix, structType)
			result = append(result, FieldPath{
				Path:     strings.Join(newJSONPrefix, "."),
				GoType:   goType,
				GoField:  newGoPrefix,
				IsStruct: true,
				Children: children,
			})
		} else if strings.HasPrefix(goType, "[]") {
			// Skip slices (generic_providers)
			continue
		} else if strings.HasPrefix(goType, "map") {
			continue
		} else {
			// Leaf field
			simpleType := simplifyType(goType)
			result = append(result, FieldPath{
				Path:    strings.Join(newJSONPrefix, "."),
				GoType:  simpleType,
				GoField: newGoPrefix,
			})
		}
	}

	return result
}

func flattenPaths(entries []FieldPath) []FieldPath {
	var result []FieldPath
	for _, e := range entries {
		if e.IsStruct {
			result = append(result, flattenPaths(e.Children)...)
		} else {
			result = append(result, e)
		}
	}
	return result
}

func simplifyType(t string) string {
	t = strings.TrimPrefix(t, "*")
	switch t {
	case "string":
		return "string"
	case "bool":
		return "bool"
	case "int", "int8", "int16", "int32", "int64":
		return "int"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "float64"
	}
	return t
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprToString(t.Elt)
	case *ast.MapType:
		return "map[" + exprToString(t.Key) + "]" + exprToString(t.Value)
	}
	return fmt.Sprintf("%T", expr)
}

func generate(paths []FieldPath, root string, fset *token.FileSet) {
	flat := flattenPaths(paths)

	var sb strings.Builder
	sb.WriteString("// Code generated by internal/genconfig; DO NOT EDIT.\n")
	sb.WriteString("package models\n\n")
	sb.WriteString("import (\n\t\"fmt\"\n\t\"strconv\"\n)\n\n")

	sb.WriteString("// ConfigPathEntry describes a single config path.\n")
	sb.WriteString("type ConfigPathEntry struct {\n\tPath string\n\tType string\n}\n\n")

	sb.WriteString("// ListConfigPaths returns all available configuration paths.\n")
	sb.WriteString("func ListConfigPaths() []ConfigPathEntry {\n")
	sb.WriteString("\treturn []ConfigPathEntry{\n")
	for _, fp := range flat {
		sb.WriteString(fmt.Sprintf("\t\t{Path: %q, Type: %q},\n", fp.Path, fp.GoType))
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// SetConfigValue sets a configuration value by dotted path.\n")
	sb.WriteString("func SetConfigValue(cfg *Config, path string, value string) error {\n")
	sb.WriteString("\tswitch path {\n")
	for _, fp := range flat {
		sb.WriteString(fmt.Sprintf("\tcase %q:\n", fp.Path))

		fieldExpr := strings.TrimPrefix(fp.GoField, "cfg.")
		switch fp.GoType {
		case "string":
			sb.WriteString(fmt.Sprintf("\t\tcfg.%s = value\n", fieldExpr))
			sb.WriteString("\t\treturn nil\n")
		case "bool":
			sb.WriteString(fmt.Sprintf("\t\tv, err := strconv.ParseBool(value)\n"))
			sb.WriteString("\t\tif err != nil {\n")
			sb.WriteString("\t\t\treturn fmt.Errorf(\"invalid value for %s: %v\", path, err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\tcfg.%s = v\n", fieldExpr))
			sb.WriteString("\t\treturn nil\n")
		case "int":
			sb.WriteString(fmt.Sprintf("\t\tv, err := strconv.Atoi(value)\n"))
			sb.WriteString("\t\tif err != nil {\n")
			sb.WriteString("\t\t\treturn fmt.Errorf(\"invalid value for %s: %v\", path, err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\tcfg.%s = v\n", fieldExpr))
			sb.WriteString("\t\treturn nil\n")
		case "float64":
			sb.WriteString(fmt.Sprintf("\t\tv, err := strconv.ParseFloat(value, 64)\n"))
			sb.WriteString("\t\tif err != nil {\n")
			sb.WriteString("\t\t\treturn fmt.Errorf(\"invalid value for %s: %v\", path, err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\tcfg.%s = v\n", fieldExpr))
			sb.WriteString("\t\treturn nil\n")
		default:
			sb.WriteString(fmt.Sprintf("\t\tcfg.%s = value\n", fieldExpr))
			sb.WriteString("\t\treturn nil\n")
		}
	}
	sb.WriteString("\tdefault:\n")
	sb.WriteString("\t\treturn fmt.Errorf(\"unknown config path: %s\", path)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// GetConfigValue returns a configuration value by dotted path.\n")
	sb.WriteString("func GetConfigValue(cfg *Config, path string) (string, error) {\n")
	sb.WriteString("\tswitch path {\n")
	for _, fp := range flat {
		sb.WriteString(fmt.Sprintf("\tcase %q:\n", fp.Path))
		fieldExpr := strings.TrimPrefix(fp.GoField, "cfg.")
		switch fp.GoType {
		case "string":
			sb.WriteString(fmt.Sprintf("\t\treturn cfg.%s, nil\n", fieldExpr))
		case "bool":
			sb.WriteString(fmt.Sprintf("\t\treturn strconv.FormatBool(cfg.%s), nil\n", fieldExpr))
		case "int":
			sb.WriteString(fmt.Sprintf("\t\treturn strconv.Itoa(cfg.%s), nil\n", fieldExpr))
		case "float64":
			sb.WriteString(fmt.Sprintf("\t\treturn strconv.FormatFloat(cfg.%s, 'f', -1, 64), nil\n", fieldExpr))
		default:
			sb.WriteString(fmt.Sprintf("\t\treturn fmt.Sprintf(\"%%v\", cfg.%s), nil\n", fieldExpr))
		}
	}
	sb.WriteString("\tdefault:\n")
	sb.WriteString("\t\treturn \"\", fmt.Errorf(\"unknown config path: %s\", path)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	outputPath := filepath.Join(root, "pkg", "models", "config_paths_gen.go")
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		panic(fmt.Sprintf("failed to write output: %v", err))
	}
	fmt.Printf("Generated %s (%d paths)\n", outputPath, len(flat))
}
